// 样式配置
const STYLES = {
  'wechat-default': {
    name: '默认公众号风格',
    styles: {
      container: 'max-width: 740px; margin: 0 auto; padding: 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.8 !important; color: #3f3f3f !important; background-color: #fff !important; word-wrap: break-word;',
      h1: 'font-size: 24px; font-weight: 600; color: #2c3e50 !important; line-height: 1.4 !important; margin: 32px 0 16px; padding-bottom: 8px; border-bottom: 2px solid #3498db;',
      h2: 'font-size: 22px; font-weight: 600; color: #2c3e50 !important; line-height: 1.4 !important; margin: 28px 0 14px; padding-left: 12px; border-left: 4px solid #3498db;',
      h3: 'font-size: 20px; font-weight: 600; color: #34495e !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      h4: 'font-size: 18px; font-weight: 600; color: #34495e !important; line-height: 1.4 !important; margin: 20px 0 10px;',
      h5: 'font-size: 17px; font-weight: 600; color: #34495e !important; line-height: 1.4 !important; margin: 18px 0 9px;',
      h6: 'font-size: 16px; font-weight: 600; color: #34495e !important; line-height: 1.4 !important; margin: 16px 0 8px;',
      p: 'margin: 16px 0 !important; line-height: 1.8 !important; color: #3f3f3f !important;',
      strong: 'font-weight: 600; color: #2c3e50 !important;',
      em: 'font-style: italic; color: #555 !important;',
      a: 'color: #3498db !important; text-decoration: none; border-bottom: 1px solid #3498db;',
      ul: 'margin: 16px 0; padding-left: 24px;',
      ol: 'margin: 16px 0; padding-left: 24px;',
      li: 'margin: 8px 0; line-height: 1.8 !important;',
      blockquote: 'margin: 16px 0; padding: 10px 16px; background-color: #fafafa !important; border-left: 3px solid #999; color: #666 !important; line-height: 1.6 !important;',
      code: 'font-family: Consolas, Monaco, "Courier New", monospace; font-size: 14px; padding: 2px 6px; background-color: #f5f5f5 !important; color: #e74c3c !important; border-radius: 3px;',
      pre: 'margin: 20px 0; padding: 16px; background-color: #2d2d2d !important; border-radius: 8px; overflow-x: auto; line-height: 1.6 !important;',
      hr: 'margin: 32px 0; border: none; border-top: 1px solid #e0e0e0;',
      img: 'max-width: 100%; max-height: 600px !important; height: auto; display: block; margin: 20px auto; border-radius: 8px;',
      table: 'width: 100%; margin: 20px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f0f0f0 !important; padding: 10px; text-align: left; border: 1px solid #e0e0e0; font-weight: 600;',
      td: 'padding: 10px; border: 1px solid #e0e0e0;',
      tr: 'border-bottom: 1px solid #e0e0e0;',
    }
  },

  'wechat-tech': {
    name: '技术风格',
    styles: {
      container: 'max-width: 740px; margin: 0 auto; padding: 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.75 !important; color: #2c3e50 !important; background-color: #fff !important; word-wrap: break-word;',
      h1: 'font-size: 26px; font-weight: 700; color: #1a1a1a !important; line-height: 1.3 !important; margin: 36px 0 18px; padding: 0 0 12px; border-bottom: 3px solid #0066cc;',
      h2: 'font-size: 22px; font-weight: 700; color: #1a1a1a !important; line-height: 1.3 !important; margin: 32px 0 16px; padding-left: 16px; padding-top: 4px; padding-bottom: 4px; border-left: 5px solid #00a67d; background: linear-gradient(to right, #f0f9ff 0%, transparent 100%);',
      h3: 'font-size: 20px; font-weight: 600; color: #2c3e50 !important; line-height: 1.4 !important; margin: 28px 0 14px; padding-left: 12px; border-left: 3px solid #ff9800;',
      h4: 'font-size: 18px; font-weight: 600; color: #34495e !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      h5: 'font-size: 17px; font-weight: 600; color: #34495e !important; line-height: 1.4 !important; margin: 20px 0 10px;',
      h6: 'font-size: 16px; font-weight: 600; color: #34495e !important; line-height: 1.4 !important; margin: 18px 0 9px;',
      p: 'margin: 18px 0 !important; line-height: 1.8 !important; color: #3a3a3a !important;',
      strong: 'font-weight: 700; color: #1a1a1a !important; background-color: #fff3cd !important; padding: 2px 4px; border-radius: 8px;',
      em: 'font-style: italic; color: #666 !important;',
      a: 'color: #0066cc !important; text-decoration: none; border-bottom: 1px solid #0066cc;',
      ul: 'margin: 18px 0; padding-left: 28px;',
      ol: 'margin: 18px 0; padding-left: 28px;',
      li: 'margin: 10px 0; line-height: 1.8 !important; color: #3a3a3a !important;',
      blockquote: 'margin: 16px 0; padding: 10px 16px; background-color: #f5f9fc !important; border-left: 3px solid #2196f3; color: #555 !important; line-height: 1.6 !important;',
      code: 'font-family: "Fira Code", Consolas, Monaco, "Courier New", monospace; font-size: 14px; padding: 3px 6px; background-color: #ffe6e6 !important; color: #d63031 !important; border-radius: 8px; font-weight: 500;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #1e1e1e !important; border-radius: 8px; overflow-x: auto; line-height: 1.6 !important; box-shadow: 0 2px 8px rgba(0,0,0,0.1);',
      hr: 'margin: 36px 0; border: none; height: 2px; background: linear-gradient(to right, transparent, #0066cc, transparent);',
      img: 'max-width: 100%; max-height: 600px !important; height: auto; display: block; margin: 24px auto; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1);',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px; box-shadow: 0 1px 4px rgba(0,0,0,0.1);',
      th: 'background-color: #0066cc !important; color: #fff !important; padding: 12px; text-align: left; border: 1px solid #0052a3; font-weight: 600;',
      td: 'padding: 12px; border: 1px solid #e0e0e0; background-color: #fff !important;',
      tr: 'border-bottom: 1px solid #e0e0e0;',
    }
  },

  'wechat-elegant': {
    name: '优雅简约',
    styles: {
      container: 'max-width: 720px; margin: 0 auto; padding: 30px 20px; font-family: "Songti SC", "SimSun", Georgia, serif; font-size: 17px; line-height: 2 !important; color: #333 !important; background-color: #fefefe !important; word-wrap: break-word;',
      h1: 'font-size: 28px; font-weight: 400; color: #1a1a1a !important; line-height: 1.5 !important; margin: 48px 0 24px; text-align: center; letter-spacing: 2px;',
      h2: 'font-size: 24px; font-weight: 400; color: #2c2c2c !important; line-height: 1.5 !important; margin: 40px 0 20px; text-align: center; letter-spacing: 1px;',
      h3: 'font-size: 20px; font-weight: 400; color: #3a3a3a !important; line-height: 1.6 !important; margin: 32px 0 16px; letter-spacing: 0.5px;',
      h4: 'font-size: 18px; font-weight: 400; color: #444 !important; line-height: 1.6 !important; margin: 28px 0 14px;',
      h5: 'font-size: 17px; font-weight: 400; color: #555 !important; line-height: 1.6 !important; margin: 24px 0 12px;',
      h6: 'font-size: 16px; font-weight: 400; color: #666 !important; line-height: 1.6 !important; margin: 20px 0 10px;',
      p: 'margin: 20px 0 !important; line-height: 2.2 !important; color: #444 !important; text-indent: 2em; letter-spacing: 0.5px;',
      strong: 'font-weight: 600; color: #1a1a1a !important;',
      em: 'font-style: italic; color: #666 !important;',
      a: 'color: #8b7355 !important; text-decoration: none; border-bottom: 1px dotted #8b7355;',
      ul: 'margin: 20px 0; padding-left: 32px;',
      ol: 'margin: 20px 0; padding-left: 32px;',
      li: 'margin: 12px 0; line-height: 2 !important;',
      blockquote: 'margin: 20px auto; padding: 12px 24px; background-color: transparent !important; border-left: 2px solid #ccc; color: #666 !important; max-width: 600px; line-height: 1.8 !important;',
      code: 'font-family: Menlo, Monaco, "Courier New", monospace; font-size: 14px; padding: 2px 6px; background-color: #f5f5f5 !important; color: #8b4513 !important; border-radius: 3px;',
      pre: 'margin: 28px 0; padding: 20px; background-color: #f9f9f9 !important; border: 1px solid #e5e5e5; border-radius: 8px; overflow-x: auto; line-height: 1.8 !important;',
      hr: 'margin: 48px auto; border: none; text-align: center; height: 1px; background-color: #e0e0e0 !important; max-width: 200px;',
      img: 'max-width: 100%; max-height: 600px !important; height: auto; display: block; margin: 32px auto; border-radius: 8px;',
      table: 'width: 100%; margin: 28px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f8f8f8 !important; padding: 12px; text-align: left; border-bottom: 2px solid #d0d0d0; font-weight: 400; color: #555 !important;',
      td: 'padding: 12px; border-bottom: 1px solid #e5e5e5;',
      tr: 'border-bottom: 1px solid #e5e5e5;',
    }
  },

  'wechat-deepread': {
    name: '深度阅读',
    styles: {
      container: 'max-width: 680px; margin: 0 auto; padding: 32px 24px; font-family: -apple-system, BlinkMacSystemFont, "SF Pro Text", "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 18px; line-height: 1.75 !important; color: #1a1a1a !important; background-color: #fff !important; word-wrap: break-word; letter-spacing: 0.01em;',
      h1: 'font-size: 32px; font-weight: 700; color: #0a0a0a !important; line-height: 1.2 !important; margin: 48px 0 24px; letter-spacing: -0.02em;',
      h2: 'font-size: 28px; font-weight: 700; color: #0a0a0a !important; line-height: 1.3 !important; margin: 40px 0 20px; letter-spacing: -0.01em;',
      h3: 'font-size: 22px; font-weight: 600; color: #1a1a1a !important; line-height: 1.4 !important; margin: 32px 0 16px;',
      h4: 'font-size: 20px; font-weight: 600; color: #2a2a2a !important; line-height: 1.5 !important; margin: 28px 0 14px;',
      h5: 'font-size: 18px; font-weight: 600; color: #3a3a3a !important; line-height: 1.5 !important; margin: 24px 0 12px;',
      h6: 'font-size: 18px; font-weight: 500; color: #4a4a4a !important; line-height: 1.5 !important; margin: 20px 0 10px;',
      p: 'margin: 24px 0 !important; line-height: 1.8 !important; color: #1a1a1a !important;',
      strong: 'font-weight: 700; color: #0a0a0a !important;',
      em: 'font-style: italic; color: #2a2a2a !important;',
      a: 'color: #0066cc !important; text-decoration: none; border-bottom: 1px solid #0066cc;',
      ul: 'margin: 24px 0; padding-left: 32px;',
      ol: 'margin: 24px 0; padding-left: 32px;',
      li: 'margin: 12px 0; line-height: 1.8 !important; color: #1a1a1a !important;',
      blockquote: 'margin: 32px 0; padding: 20px 24px; background-color: #f8f9fa !important; border-left: 4px solid #0a0a0a; color: #1a1a1a !important; font-size: 17px; line-height: 1.7 !important; font-style: normal;',
      code: 'font-family: "SF Mono", Consolas, Monaco, "Courier New", monospace; font-size: 16px; padding: 2px 6px; background-color: #f5f5f5 !important; color: #d73a49 !important; border-radius: 3px;',
      pre: 'margin: 32px 0; padding: 24px; background-color: #f6f8fa !important; border-radius: 8px; overflow-x: auto; line-height: 1.6 !important; border: 1px solid #e1e4e8;',
      hr: 'margin: 48px 0; border: none; height: 1px; background-color: #e1e4e8 !important;',
      img: 'max-width: 100%; max-height: 600px !important; height: auto; display: block; margin: 32px auto; border-radius: 8px;',
      table: 'width: 100%; margin: 32px 0; border-collapse: collapse; font-size: 16px;',
      th: 'background-color: #f6f8fa !important; padding: 12px 16px; text-align: left; border: 1px solid #e1e4e8; font-weight: 600; color: #1a1a1a !important;',
      td: 'padding: 12px 16px; border: 1px solid #e1e4e8; color: #1a1a1a !important;',
      tr: 'border-bottom: 1px solid #e1e4e8;',
    }
  },

  'wechat-magazine': {
    name: '杂志风格',
    styles: {
      container: 'max-width: 700px; margin: 0 auto; padding: 40px 28px; font-family: -apple-system, "Helvetica Neue", Arial, sans-serif; font-size: 17px; line-height: 1.7 !important; color: #000 !important; background-color: #fff !important; word-wrap: break-word;',
      h1: 'font-size: 42px; font-weight: 900; color: #000 !important; line-height: 1.1 !important; margin: 56px 0 32px; text-transform: uppercase; letter-spacing: 0.05em; border-top: 6px solid #000; border-bottom: 6px solid #000; padding: 24px 0;',
      h2: 'font-size: 32px; font-weight: 800; color: #000 !important; line-height: 1.2 !important; margin: 48px 0 24px; letter-spacing: 0.02em; border-left: 8px solid #000; padding-left: 20px; background: linear-gradient(to right, #f5f5f5 0%, transparent 100%);',
      h3: 'font-size: 26px; font-weight: 700; color: #000 !important; line-height: 1.3 !important; margin: 40px 0 20px; text-transform: uppercase; letter-spacing: 0.08em; border-bottom: 3px solid #000; padding-bottom: 12px;',
      h4: 'font-size: 22px; font-weight: 700; color: #1a1a1a !important; line-height: 1.4 !important; margin: 32px 0 16px; font-style: italic;',
      h5: 'font-size: 19px; font-weight: 700; color: #2a2a2a !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h6: 'font-size: 17px; font-weight: 700; color: #3a3a3a !important; line-height: 1.4 !important; margin: 24px 0 12px; text-transform: uppercase; letter-spacing: 0.1em;',
      p: 'margin: 20px 0 !important; line-height: 1.75 !important; color: #1a1a1a !important; font-size: 17px;',
      strong: 'font-weight: 900; color: #000 !important; background-color: #ffeb3b !important; padding: 2px 4px;',
      em: 'font-style: italic; color: #000 !important; font-family: Georgia, serif;',
      a: 'color: #000 !important; text-decoration: none; border-bottom: 3px solid #000; font-weight: 700;',
      ul: 'margin: 24px 0; padding-left: 0; list-style: none;',
      ol: 'margin: 24px 0; padding-left: 0; list-style: none; counter-reset: magazine-counter;',
      li: 'margin: 16px 0; line-height: 1.7 !important; color: #1a1a1a !important; padding-left: 40px; position: relative;',
      blockquote: 'margin: 40px 0; padding: 32px 40px; background-color: #000 !important; color: #fff !important; font-size: 24px; line-height: 1.5 !important; font-weight: 700; font-style: italic; border-left: 8px solid #ffeb3b;',
      code: 'font-family: "Courier New", Courier, monospace; font-size: 15px; padding: 3px 8px; background-color: #000 !important; color: #ffeb3b !important; font-weight: 700;',
      pre: 'margin: 32px 0; padding: 28px; background-color: #000 !important; color: #ffeb3b !important; overflow-x: auto; line-height: 1.6 !important; border: 4px solid #ffeb3b; font-weight: 700;',
      hr: 'margin: 56px auto; border: none; height: 4px; background-color: #000 !important; max-width: 120px;',
      img: 'max-width: 100%; max-height: 600px !important; height: auto; display: block; margin: 40px auto; border: 8px solid #000;',
      table: 'width: 100%; margin: 32px 0; border-collapse: collapse; font-size: 16px; border: 3px solid #000;',
      th: 'background-color: #000 !important; color: #fff !important; padding: 16px; text-align: left; border: 2px solid #000; font-weight: 800; text-transform: uppercase; letter-spacing: 0.05em;',
      td: 'padding: 16px; border: 2px solid #000; background-color: #f5f5f5 !important;',
      tr: 'border: 2px solid #000;',
    }
  },

  'wechat-nyt': {
    name: '纽约时报',
    styles: {
      container: 'max-width: 680px; margin: 0 auto; padding: 48px 32px; font-family: Georgia, "Times New Roman", Times, serif; font-size: 18px; line-height: 1.8 !important; color: #121212 !important; background-color: #fff !important; word-wrap: break-word;',
      h1: 'font-size: 42px; font-weight: 700; color: #000 !important; line-height: 1.2 !important; margin: 56px 0 16px; font-family: Georgia, serif; letter-spacing: -0.02em; border-bottom: 1px solid #000; padding-bottom: 16px;',
      h2: 'font-size: 32px; font-weight: 700; color: #000 !important; line-height: 1.3 !important; margin: 48px 0 16px; font-family: Georgia, serif; letter-spacing: -0.01em;',
      h3: 'font-size: 24px; font-weight: 700; color: #121212 !important; line-height: 1.4 !important; margin: 40px 0 16px; font-family: Georgia, serif;',
      h4: 'font-size: 20px; font-weight: 700; color: #1a1a1a !important; line-height: 1.5 !important; margin: 32px 0 12px; font-family: Georgia, serif;',
      h5: 'font-size: 18px; font-weight: 700; color: #2a2a2a !important; line-height: 1.5 !important; margin: 28px 0 12px; font-family: Georgia, serif;',
      h6: 'font-size: 16px; font-weight: 700; color: #3a3a3a !important; line-height: 1.5 !important; margin: 24px 0 10px; font-family: Georgia, serif; font-style: italic;',
      p: 'margin: 20px 0 !important; line-height: 1.8 !important; color: #121212 !important; text-align: left;',
      strong: 'font-weight: 700; color: #000 !important;',
      em: 'font-style: italic; color: #121212 !important;',
      a: 'color: #326891 !important; text-decoration: none; border-bottom: 1px solid #326891; word-break: break-all;',
      ul: 'margin: 24px 0; padding-left: 40px;',
      ol: 'margin: 24px 0; padding-left: 40px;',
      li: 'margin: 12px 0; line-height: 1.8 !important; color: #121212 !important; text-align: left;',
      blockquote: 'margin: 32px 0; padding: 20px 32px; background-color: #f7f7f7 !important; border-left: 5px solid #121212; color: #121212 !important; font-size: 20px; line-height: 1.7 !important; font-style: italic; font-family: Georgia, serif;',
      code: 'font-family: "Courier New", Courier, monospace; font-size: 16px; padding: 2px 6px; background-color: #f0f0f0 !important; color: #666 !important; border: 1px solid #ddd;',
      pre: 'margin: 28px 0; padding: 24px; background-color: #f7f7f7 !important; border: 1px solid #ddd; overflow-x: auto; line-height: 1.6 !important;',
      hr: 'margin: 48px auto; border: none; height: 1px; background-color: #ddd !important; max-width: 100px;',
      img: 'max-width: 100%; max-height: 600px !important; height: auto; display: block; margin: 32px auto; border: 1px solid #ddd;',
      table: 'width: 100%; margin: 32px 0; border-collapse: collapse; font-size: 16px; border: 1px solid #ddd;',
      th: 'background-color: #f7f7f7 !important; padding: 14px 16px; text-align: left; border: 1px solid #ddd; font-weight: 700; color: #121212 !important; font-family: Georgia, serif;',
      td: 'padding: 14px 16px; border: 1px solid #ddd; color: #121212 !important;',
      tr: 'border-bottom: 1px solid #ddd;',
    }
  },

  'wechat-ft': {
    name: '金融时报',
    styles: {
      container: 'max-width: 680px; margin: 0 auto; padding: 40px 32px; font-family: Georgia, "Times New Roman", Times, serif; font-size: 17px; line-height: 1.75 !important; color: #33302e !important; background-color: #fff1e5 !important; word-wrap: break-word;',
      h1: 'font-size: 38px; font-weight: 600; color: #000 !important; line-height: 1.2 !important; margin: 56px 0 24px; font-family: Georgia, serif; letter-spacing: -0.01em; border-bottom: 4px solid #990f3d; padding-bottom: 16px;',
      h2: 'font-size: 30px; font-weight: 600; color: #990f3d !important; line-height: 1.3 !important; margin: 48px 0 20px; font-family: Georgia, serif; border-left: 6px solid #990f3d; padding-left: 20px;',
      h3: 'font-size: 24px; font-weight: 600; color: #33302e !important; line-height: 1.4 !important; margin: 40px 0 16px; font-family: Georgia, serif; border-bottom: 2px solid #cec6b9; padding-bottom: 8px;',
      h4: 'font-size: 20px; font-weight: 600; color: #33302e !important; line-height: 1.5 !important; margin: 32px 0 12px; font-family: Georgia, serif;',
      h5: 'font-size: 18px; font-weight: 600; color: #33302e !important; line-height: 1.5 !important; margin: 28px 0 12px; font-family: Georgia, serif;',
      h6: 'font-size: 17px; font-weight: 600; color: #33302e !important; line-height: 1.5 !important; margin: 24px 0 10px; font-family: Georgia, serif; font-style: italic;',
      p: 'margin: 20px 0 !important; line-height: 1.75 !important; color: #33302e !important;',
      strong: 'font-weight: 700; color: #990f3d !important;',
      em: 'font-style: italic; color: #33302e !important;',
      a: 'color: #0d7680 !important; text-decoration: none; border-bottom: 2px solid #0d7680; font-weight: 600;',
      ul: 'margin: 24px 0; padding-left: 32px;',
      ol: 'margin: 24px 0; padding-left: 32px;',
      li: 'margin: 12px 0; line-height: 1.75 !important; color: #33302e !important;',
      blockquote: 'margin: 32px 0; padding: 24px 28px; background-color: #990f3d !important; color: #fff !important; font-size: 19px; line-height: 1.7 !important; font-style: italic; font-family: Georgia, serif; border-left: 6px solid #fff1e5;',
      code: 'font-family: "Courier New", Courier, monospace; font-size: 15px; padding: 3px 8px; background-color: #fff !important; color: #990f3d !important; border: 1px solid #cec6b9; font-weight: 600;',
      pre: 'margin: 28px 0; padding: 24px; background-color: #fff !important; border-left: 4px solid #990f3d; overflow-x: auto; line-height: 1.6 !important;',
      hr: 'margin: 48px auto; border: none; height: 2px; background-color: #990f3d !important; max-width: 80px;',
      img: 'max-width: 100%; max-height: 600px !important; height: auto; display: block; margin: 32px auto; border: 3px solid #990f3d;',
      table: 'width: 100%; margin: 32px 0; border-collapse: collapse; font-size: 16px; background-color: #fff !important;',
      th: 'background-color: #990f3d !important; color: #fff !important; padding: 14px 16px; text-align: left; border: 1px solid #990f3d; font-weight: 700; font-family: Georgia, serif;',
      td: 'padding: 14px 16px; border: 1px solid #cec6b9; color: #33302e !important; background-color: #fff !important;',
      tr: 'border-bottom: 1px solid #cec6b9;',
    }
  },

  'wechat-jonyive': {
    name: 'Jony Ive',
    styles: {
      container: 'max-width: 620px; margin: 0 auto; padding: 80px 40px; font-family: -apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", "Helvetica Neue", Arial, sans-serif; font-size: 17px; line-height: 1.6 !important; color: #6e6e73 !important; background-color: #fbfbfd !important; word-wrap: break-word;',
      h1: 'font-size: 56px; font-weight: 200; color: #1d1d1f !important; line-height: 1.05 !important; margin: 96px 0 48px; letter-spacing: -0.03em;',
      h2: 'font-size: 40px; font-weight: 300; color: #1d1d1f !important; line-height: 1.1 !important; margin: 80px 0 40px; letter-spacing: -0.02em;',
      h3: 'font-size: 28px; font-weight: 400; color: #1d1d1f !important; line-height: 1.15 !important; margin: 64px 0 32px; letter-spacing: -0.01em;',
      h4: 'font-size: 21px; font-weight: 500; color: #1d1d1f !important; line-height: 1.2 !important; margin: 48px 0 24px;',
      h5: 'font-size: 19px; font-weight: 500; color: #1d1d1f !important; line-height: 1.25 !important; margin: 40px 0 20px;',
      h6: 'font-size: 17px; font-weight: 500; color: #1d1d1f !important; line-height: 1.3 !important; margin: 32px 0 16px;',
      p: 'margin: 32px 0 !important; line-height: 1.6 !important; color: #6e6e73 !important; font-weight: 300;',
      strong: 'font-weight: 500; color: #1d1d1f !important;',
      em: 'font-style: normal; color: #6e6e73 !important; font-weight: 300;',
      a: 'color: #06c !important; text-decoration: none; font-weight: 400;',
      ul: 'margin: 32px 0; padding-left: 0; list-style: none;',
      ol: 'margin: 32px 0; padding-left: 0; list-style: none;',
      li: 'margin: 20px 0; line-height: 1.6 !important; color: #6e6e73 !important; padding-left: 32px; position: relative; font-weight: 300;',
      blockquote: 'margin: 64px auto; padding: 0; background-color: transparent !important; border-left: none; color: #1d1d1f !important; font-size: 28px; line-height: 1.3 !important; font-weight: 300; text-align: center; max-width: 520px; font-style: normal;',
      code: 'font-family: "SF Mono", Monaco, Menlo, monospace; font-size: 15px; padding: 2px 6px; background-color: #f5f5f7 !important; color: #6e6e73 !important; border-radius: 8px; font-weight: 400;',
      pre: 'margin: 48px 0; padding: 32px; background-color: #f5f5f7 !important; border-radius: 12px; overflow-x: auto; line-height: 1.5 !important;',
      hr: 'margin: 96px auto; border: none; height: 1px; background-color: #d2d2d7 !important; max-width: 64px;',
      img: 'max-width: 100%; max-height: 600px !important; height: auto; display: block; margin: 64px auto; border-radius: 12px;',
      table: 'width: 100%; margin: 48px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f5f5f7 !important; padding: 16px 20px; text-align: left; border: none; font-weight: 500; color: #1d1d1f !important;',
      td: 'padding: 16px 20px; border: none; border-top: 1px solid #d2d2d7; color: #6e6e73 !important; font-weight: 300;',
      tr: 'border: none;',
    }
  },

  'wechat-wired': {
    name: 'Wired 连线',
    styles: {
      container: 'max-width: 720px; margin: 0 auto; padding: 40px 32px; font-family: -apple-system, BlinkMacSystemFont, "Helvetica Neue", Arial, sans-serif; font-size: 18px; line-height: 1.7 !important; color: #000 !important; background-color: #fff !important; word-wrap: break-word;',
      h1: 'font-size: 48px; font-weight: 900; color: #000 !important; line-height: 1.1 !important; margin: 56px 0 32px; letter-spacing: -0.02em; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent !important;',
      h2: 'font-size: 36px; font-weight: 800; color: #000 !important; line-height: 1.2 !important; margin: 48px 0 24px; letter-spacing: -0.01em; background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent !important;',
      h3: 'font-size: 28px; font-weight: 700; color: #000 !important; line-height: 1.3 !important; margin: 40px 0 20px; background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent !important;',
      h4: 'font-size: 24px; font-weight: 700; color: #1a1a1a !important; line-height: 1.4 !important; margin: 32px 0 16px;',
      h5: 'font-size: 20px; font-weight: 700; color: #2a2a2a !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h6: 'font-size: 18px; font-weight: 700; color: #3a3a3a !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 24px 0 !important; line-height: 1.75 !important; color: #1a1a1a !important; font-size: 18px;',
      strong: 'font-weight: 800; color: #000 !important; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent !important;',
      em: 'font-style: italic; color: #1a1a1a !important;',
      a: 'color: #667eea !important; text-decoration: none; border-bottom: 2px solid #667eea; font-weight: 600;',
      ul: 'margin: 24px 0; padding-left: 32px;',
      ol: 'margin: 24px 0; padding-left: 32px;',
      li: 'margin: 12px 0; line-height: 1.75 !important; color: #1a1a1a !important;',
      blockquote: 'margin: 40px 0; padding: 24px 32px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #fff !important; font-size: 22px; line-height: 1.6 !important; font-weight: 600; border-left: 6px solid #fff;',
      code: 'font-family: "Fira Code", Consolas, Monaco, monospace; font-size: 16px; padding: 3px 8px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #fff !important; font-weight: 600; border-radius: 8px;',
      pre: 'margin: 32px 0; padding: 28px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #fff !important; overflow-x: auto; line-height: 1.6 !important; border-radius: 12px; font-weight: 600;',
      hr: 'margin: 56px 0; border: none; height: 3px; background: linear-gradient(to right, #667eea, #764ba2, #f093fb);',
      img: 'max-width: 100%; max-height: 600px !important; height: auto; display: block; margin: 40px auto; border-radius: 12px; box-shadow: 0 8px 24px rgba(102,126,234,0.3);',
      table: 'width: 100%; margin: 32px 0; border-collapse: collapse; font-size: 17px;',
      th: 'background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #fff !important; padding: 16px 20px; text-align: left; border: none; font-weight: 700;',
      td: 'padding: 16px 20px; border-bottom: 2px solid #f0f0f0; color: #1a1a1a !important;',
      tr: 'border: none;',
    }
  },

  'wechat-medium': {
    name: 'Medium 长文',
    styles: {
      container: 'max-width: 680px; margin: 0 auto; padding: 48px 32px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 21px; line-height: 1.58 !important; color: #242424 !important; background-color: #fff !important; word-wrap: break-word; letter-spacing: -0.003em;',
      h1: 'font-size: 42px; font-weight: 700; color: #242424 !important; line-height: 1.15 !important; margin: 56px 0 24px; letter-spacing: -0.022em; font-family: Georgia, "Times New Roman", serif;',
      h2: 'font-size: 34px; font-weight: 700; color: #242424 !important; line-height: 1.2 !important; margin: 48px 0 20px; letter-spacing: -0.019em; font-family: Georgia, "Times New Roman", serif;',
      h3: 'font-size: 28px; font-weight: 700; color: #242424 !important; line-height: 1.25 !important; margin: 40px 0 16px; letter-spacing: -0.014em; font-family: Georgia, "Times New Roman", serif;',
      h4: 'font-size: 24px; font-weight: 700; color: #242424 !important; line-height: 1.3 !important; margin: 32px 0 12px; font-family: Georgia, "Times New Roman", serif;',
      h5: 'font-size: 21px; font-weight: 700; color: #242424 !important; line-height: 1.35 !important; margin: 28px 0 10px; font-family: Georgia, "Times New Roman", serif;',
      h6: 'font-size: 19px; font-weight: 700; color: #242424 !important; line-height: 1.4 !important; margin: 24px 0 8px; font-family: Georgia, "Times New Roman", serif;',
      p: 'margin: 32px 0 !important; line-height: 1.58 !important; color: #242424 !important; font-size: 21px; letter-spacing: -0.003em;',
      strong: 'font-weight: 700; color: #242424 !important;',
      em: 'font-style: italic; color: #242424 !important;',
      a: 'color: #242424 !important; text-decoration: none; border-bottom: 1px solid #242424;',
      ul: 'margin: 32px 0; padding-left: 40px;',
      ol: 'margin: 32px 0; padding-left: 40px;',
      li: 'margin: 16px 0; line-height: 1.58 !important; color: #242424 !important; font-size: 21px;',
      blockquote: 'margin: 48px 0; padding: 0 32px; border-left: 3px solid #242424; color: #242424 !important; font-size: 24px; line-height: 1.48 !important; font-style: italic; font-family: Georgia, "Times New Roman", serif;',
      code: 'font-family: Menlo, Monaco, "Courier New", monospace; font-size: 18px; padding: 3px 6px; background-color: #f5f5f5 !important; color: #d73a49 !important; border-radius: 3px;',
      pre: 'margin: 40px 0; padding: 24px; background-color: #f7f7f7 !important; border-radius: 8px; overflow-x: auto; line-height: 1.5 !important;',
      hr: 'margin: 56px auto; border: none; text-align: center; height: 1px; background-color: #e6e6e6 !important; max-width: 400px;',
      img: 'max-width: 100%; max-height: 600px !important; height: auto; display: block; margin: 40px auto;',
      table: 'width: 100%; margin: 40px 0; border-collapse: collapse; font-size: 19px;',
      th: 'background-color: #f7f7f7 !important; padding: 14px 18px; text-align: left; border-bottom: 2px solid #e6e6e6; font-weight: 700; color: #242424 !important;',
      td: 'padding: 14px 18px; border-bottom: 1px solid #e6e6e6; color: #242424 !important;',
      tr: 'border: none;',
    }
  },

  'wechat-apple': {
    name: 'Apple 极简',
    styles: {
      container: 'max-width: 640px; margin: 0 auto; padding: 96px 48px; font-family: -apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", "Helvetica Neue", Arial, sans-serif; font-size: 17px; line-height: 1.5 !important; color: #86868b !important; background-color: #fbfbfd !important; word-wrap: break-word;',
      h1: 'font-size: 64px; font-weight: 600; color: #1d1d1f !important; line-height: 1.05 !important; margin: 112px 0 56px; letter-spacing: -0.015em;',
      h2: 'font-size: 48px; font-weight: 600; color: #1d1d1f !important; line-height: 1.08 !important; margin: 96px 0 48px; letter-spacing: -0.012em;',
      h3: 'font-size: 32px; font-weight: 600; color: #1d1d1f !important; line-height: 1.125 !important; margin: 80px 0 40px; letter-spacing: -0.009em;',
      h4: 'font-size: 24px; font-weight: 600; color: #1d1d1f !important; line-height: 1.17 !important; margin: 64px 0 32px;',
      h5: 'font-size: 21px; font-weight: 600; color: #1d1d1f !important; line-height: 1.2 !important; margin: 56px 0 28px;',
      h6: 'font-size: 19px; font-weight: 600; color: #1d1d1f !important; line-height: 1.25 !important; margin: 48px 0 24px;',
      p: 'margin: 40px 0 !important; line-height: 1.5 !important; color: #86868b !important; font-size: 17px;',
      strong: 'font-weight: 600; color: #1d1d1f !important;',
      em: 'font-style: normal; color: #86868b !important;',
      a: 'color: #06c !important; text-decoration: none;',
      ul: 'margin: 40px 0; padding-left: 0; list-style: none;',
      ol: 'margin: 40px 0; padding-left: 0; list-style: none;',
      li: 'margin: 24px 0; line-height: 1.5 !important; color: #86868b !important; padding-left: 28px; position: relative;',
      blockquote: 'margin: 80px auto; padding: 0; background-color: transparent !important; border-left: none; color: #1d1d1f !important; font-size: 32px; line-height: 1.25 !important; font-weight: 600; text-align: center; max-width: 560px; font-style: normal;',
      code: 'font-family: "SF Mono", Monaco, Menlo, monospace; font-size: 15px; padding: 2px 6px; background-color: #f5f5f7 !important; color: #86868b !important; border-radius: 8px;',
      pre: 'margin: 56px 0; padding: 32px; background-color: #f5f5f7 !important; border-radius: 18px; overflow-x: auto; line-height: 1.47 !important;',
      hr: 'margin: 112px auto; border: none; height: 1px; background-color: #d2d2d7 !important; max-width: 48px;',
      img: 'max-width: 100%; max-height: 600px !important; height: auto; display: block; margin: 80px auto; border-radius: 18px;',
      table: 'width: 100%; margin: 56px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f5f5f7 !important; padding: 18px 24px; text-align: left; border: none; font-weight: 600; color: #1d1d1f !important;',
      td: 'padding: 18px 24px; border: none; border-top: 1px solid #d2d2d7; color: #86868b !important;',
      tr: 'border: none;',
    }
  },

  'wechat-aicoder': {
    name: 'AI Coder 特调',
    styles: {
      container: 'max-width: 720px; margin: 0 auto; padding: 48px 32px; font-family: -apple-system, BlinkMacSystemFont, "SF Pro Text", "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 18px; line-height: 1.65 !important; color: #1a1a1a !important; background-color: #fff !important; word-wrap: break-word; letter-spacing: -0.002em;',
      h1: 'font-size: 44px; font-weight: 700; color: #000 !important; line-height: 1.15 !important; margin: 56px 0 28px; letter-spacing: -0.02em; background: linear-gradient(135deg, #0066ff 0%, #00ccff 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent !important;',
      h2: 'font-size: 34px; font-weight: 700; color: #000 !important; line-height: 1.2 !important; margin: 48px 0 24px; letter-spacing: -0.015em; background: linear-gradient(135deg, #0066ff 0%, #00ccff 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent !important;',
      h3: 'font-size: 26px; font-weight: 600; color: #1a1a1a !important; line-height: 1.3 !important; margin: 40px 0 20px; letter-spacing: -0.01em;',
      h4: 'font-size: 22px; font-weight: 600; color: #2a2a2a !important; line-height: 1.4 !important; margin: 32px 0 16px;',
      h5: 'font-size: 20px; font-weight: 600; color: #3a3a3a !important; line-height: 1.45 !important; margin: 28px 0 14px;',
      h6: 'font-size: 18px; font-weight: 600; color: #4a4a4a !important; line-height: 1.5 !important; margin: 24px 0 12px;',
      p: 'margin: 28px 0 !important; line-height: 1.7 !important; color: #1a1a1a !important; font-size: 18px;',
      strong: 'font-weight: 700; color: #000 !important; background-color: #e6f3ff !important; padding: 2px 4px; border-radius: 8px;',
      em: 'font-style: italic; color: #4a4a4a !important;',
      a: 'color: #0066ff !important; text-decoration: none; border-bottom: 1px solid #0066ff; font-weight: 500;',
      ul: 'margin: 28px 0; padding-left: 32px;',
      ol: 'margin: 28px 0; padding-left: 32px;',
      li: 'margin: 14px 0; line-height: 1.7 !important; color: #1a1a1a !important; font-size: 18px;',
      blockquote: 'margin: 40px 0; padding: 20px 28px; background-color: #f8f9fa !important; border-left: 4px solid #0066ff; color: #1a1a1a !important; font-size: 19px; line-height: 1.65 !important; font-style: italic;',
      code: 'font-family: "SF Mono", "Fira Code", Consolas, Monaco, monospace; font-size: 16px; padding: 3px 6px; background-color: #f5f5f7 !important; color: #d73a49 !important; border-radius: 8px; font-weight: 500;',
      pre: 'margin: 32px 0; padding: 24px; background-color: #0d1117 !important; color: #c9d1d9 !important; border-radius: 8px; overflow-x: auto; line-height: 1.6 !important;',
      hr: 'margin: 56px auto; border: none; height: 2px; background: linear-gradient(to right, transparent, #0066ff, transparent); max-width: 200px;',
      img: 'max-width: 100%; max-height: 600px !important; height: auto; display: block; margin: 40px auto; border-radius: 8px; box-shadow: 0 4px 12px rgba(0,102,255,0.15);',
      table: 'width: 100%; margin: 32px 0; border-collapse: collapse; font-size: 17px;',
      th: 'background-color: #f8f9fa !important; padding: 14px 18px; text-align: left; border: 1px solid #e1e4e8; font-weight: 600; color: #1a1a1a !important;',
      td: 'padding: 14px 18px; border: 1px solid #e1e4e8; color: #1a1a1a !important;',
      tr: 'border-bottom: 1px solid #e1e4e8;',
    }
  },

  'wechat-anthropic': {
    name: 'Anthropic Claude',
    styles: {
      container: 'max-width: 700px; margin: 0 auto; padding: 56px 40px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Arial, sans-serif; font-size: 18px; line-height: 1.7 !important; color: #2b2b2b !important; background-color: #faf9f7 !important; word-wrap: break-word; letter-spacing: -0.01em;',
      h1: 'font-size: 48px; font-weight: 600; color: #191919 !important; line-height: 1.15 !important; margin: 64px 0 32px; letter-spacing: -0.025em; background: linear-gradient(135deg, #C15F3C 0%, #e97d5b 50%, #CC8B7A 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent !important;',
      h2: 'font-size: 36px; font-weight: 600; color: #191919 !important; line-height: 1.25 !important; margin: 56px 0 28px; letter-spacing: -0.02em; background: linear-gradient(135deg, #C15F3C 0%, #9DC88D 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent !important;',
      h3: 'font-size: 28px; font-weight: 600; color: #2b2b2b !important; line-height: 1.3 !important; margin: 48px 0 24px; letter-spacing: -0.015em;',
      h4: 'font-size: 24px; font-weight: 600; color: #3a3a3a !important; line-height: 1.4 !important; margin: 40px 0 20px; letter-spacing: -0.01em;',
      h5: 'font-size: 20px; font-weight: 600; color: #4a4a4a !important; line-height: 1.45 !important; margin: 32px 0 16px;',
      h6: 'font-size: 18px; font-weight: 600; color: #5a5a5a !important; line-height: 1.5 !important; margin: 28px 0 14px;',
      p: 'margin: 32px 0 !important; line-height: 1.75 !important; color: #2b2b2b !important; font-size: 18px; letter-spacing: -0.005em;',
      strong: 'font-weight: 600; color: #C15F3C !important; background-color: rgba(193, 95, 60, 0.08) !important; padding: 2px 6px; border-radius: 3px;',
      em: 'font-style: italic; color: #5a5a5a !important;',
      a: 'color: #C15F3C !important; text-decoration: none; border-bottom: 1px solid rgba(193, 95, 60, 0.4); font-weight: 500;',
      ul: 'margin: 32px 0; padding-left: 32px;',
      ol: 'margin: 32px 0; padding-left: 32px;',
      li: 'margin: 16px 0; line-height: 1.75 !important; color: #2b2b2b !important; font-size: 18px;',
      blockquote: 'margin: 48px 0; padding: 24px 32px; background: linear-gradient(135deg, rgba(193, 95, 60, 0.06) 0%, rgba(157, 200, 141, 0.06) 100%); border-left: 4px solid #C15F3C; color: #2b2b2b !important; font-size: 20px; line-height: 1.65 !important; font-style: italic; border-radius: 8px;',
      code: 'font-family: "SF Mono", Consolas, Monaco, monospace; font-size: 16px; padding: 3px 8px; background-color: rgba(193, 95, 60, 0.08) !important; color: #C15F3C !important; border-radius: 8px; font-weight: 500; border: 1px solid rgba(193, 95, 60, 0.15);',
      pre: 'margin: 40px 0; padding: 28px; background: linear-gradient(135deg, #2b2b2b 0%, #3a3a3a 100%); color: #f5f5f5 !important; border-radius: 12px; overflow-x: auto; line-height: 1.6 !important; box-shadow: 0 4px 20px rgba(193, 95, 60, 0.15);',
      hr: 'margin: 64px auto; border: none; height: 2px; background: linear-gradient(to right, transparent, rgba(193, 95, 60, 0.3), rgba(157, 200, 141, 0.3), transparent); max-width: 240px;',
      img: 'max-width: 100%; max-height: 600px !important; height: auto; display: block; margin: 48px auto; border-radius: 12px; box-shadow: 0 8px 32px rgba(193, 95, 60, 0.12);',
      table: 'width: 100%; margin: 40px 0; border-collapse: collapse; font-size: 17px; border-radius: 8px; overflow: hidden;',
      th: 'background: linear-gradient(135deg, rgba(193, 95, 60, 0.08) 0%, rgba(157, 200, 141, 0.08) 100%); padding: 16px 20px; text-align: left; border: none; font-weight: 600; color: #2b2b2b !important; border-bottom: 2px solid rgba(193, 95, 60, 0.2);',
      td: 'padding: 16px 20px; border: none; border-bottom: 1px solid rgba(193, 95, 60, 0.1); color: #2b2b2b !important;',
      tr: 'border: none;',
    }
  }
};
