name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      short_sha: ${{ steps.vars.outputs.short_sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Short Commit Hash
        id: vars
        run: echo "short_sha=$(git rev-parse --short=6 HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/huasheng_editor:${{ steps.vars.outputs.short_sha }} .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/huasheng_editor:${{ steps.vars.outputs.short_sha }}
#
#  update-images:
#    runs-on: ubuntu-latest
#    needs: build-and-push
#    steps:
#      - name: Checkout argo repo
#        uses: actions/checkout@v4
#        with:
#          repository: xieyos/argo
#          token: ${{ secrets.APP_REPO_TOKEN }}
#          path: argo-repo
#
#      - name: Update image tags in yaml files
#        run: |
#          cd argo-repo/xieyos-app/xieyos-cloud
#          sed -i "s|image: ghcr.io/${{ github.repository }}/.*:.*|image: ghcr.io/${{ github.repository }}/huasheng_editor:${{ needs.build-and-push.outputs.short_sha }}|g" xieyos-ui-server-stateful-set.yaml
#
#      - name: Commit and Push Changes
#        run: |
#          cd argo-repo
#          git config user.name "xieyos"
#          git config user.email "gxieyos@163.com"
#          git add xieyos-app/xieyos-cloud/*.yaml
#          git commit -m "Update k8s huasheng_editor image to ${{ needs.build-and-push.outputs.short_sha }}"
#          git push origin main